### ISSUE TITLE
Inspiration: zigbee2mqtt's API output

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/schemas#73]
This is what zigbee2MQTT's API might output:

https://github.com/Koenkk/zigbee-herdsman-converters/blob/0c34d244d97d0213ae56274f4da18a4a65b4ca3c/lib/exposes.js#L507

from [here](https://github.com/Koenkk/zigbee2mqtt/issues/6334)

**Comment by mrstegeman** [comment]
@benfrancis is working with the W3C via the [Web Thing Protocol Community Group](https://www.w3.org/community/web-thing-protocol/) to develop the official protocol bindings, but my guess is that they'll be strongly inspired by our [existing API](https://webthings.io/api/), rather than something completely different.

**Comment by flatsiedatsie** [comment]
I know. Guess it's not interesting.
